create table tpl_mro_maxrsrp_eutr_day (
omc_id  integer,
int_id  integer,
related_enodeb  integer,
enodeb_name  varchar2(128),
vendor_id  integer,
enb_id  integer,
m_eutrancell_id  varchar2(20),
m_celllocalid  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
maxrsrp_0  integer,
maxrsrp_1  integer,
maxrsrp_2  integer,
maxrsrp_3  integer,
maxrsrp_4  integer,
maxrsrp_5  integer,
maxrsrp_6  integer,
maxrsrp_7  integer,
maxrsrp_8  integer,
maxrsrp_9  integer,
maxrsrp_10  integer,
total_num  integer
);


create table tpl_mro_rsrpdiff_eutr_day (
omc_id  integer,
int_id  integer,
related_enodeb  integer,
enodeb_name  varchar2(128),
vendor_id  integer,
enb_id  integer,
m_eutrancell_id  varchar2(20),
m_celllocalid  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
rsrpdiff_0  integer,
rsrpdiff_1  integer,
rsrpdiff_2  integer,
rsrpdiff_3  integer,
rsrpdiff_4  integer,
rsrpdiff_5  integer,
rsrpdiff_6  integer,
rsrpdiff_7  integer,
rsrpdiff_8  integer,
rsrpdiff_9  integer,
rsrpdiff_10  integer,
rsrpdiff_11  integer,
rsrpdiff_12  integer,
rsrpdiff_13  integer,
rsrpdiff_14  integer,
rsrpdiff_15  integer,
rsrpdiff_16  integer,
rsrpdiff_17  integer,
rsrpdiff_18  integer,
rsrpdiff_19  integer,
rsrpdiff_20  integer,
rsrpdiff_21  integer,
rsrpdiff_22  integer,
rsrpdiff_23  integer,
rsrpdiff_24  integer,
rsrpdiff_25  integer,
rsrpdiff_26  integer
);

create table tpl_mro_overlap_day (
omc_id  integer,
int_id  integer,
related_enodeb  integer,
enodeb_name  varchar2(128),
vendor_id  integer,
enb_id  integer,
m_eutrancell_id  varchar2(20),
m_celllocalid  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
diffdbm_0  integer,
diffdbm_1  integer,
diffdbm_2  integer,
diffdbm_3  integer,
diffdbm_4  integer,
diffdbm_5  integer,
diffdbm_6  integer,
diffdbm_7  integer,
diffdbm_8  integer,
diffdbm_9  integer,
diffdbm_10  integer,
diffdbm_11  integer,
diffdbm_12  integer,
diffdbm_13  integer,
diffdbm_14  integer,
diffdbm_15  integer,
diffdbm_16  integer,
diffdbm_17  integer,
diffdbm_18  integer,
diffdbm_19  integer,
diffdbm_20  integer,
diffdbm_21  integer,
diffdbm_22  integer,
diffdbm_23  integer,
diffdbm_24  integer,
diffdbm_25  integer,
diffdbm_26  integer,
diffdbm_27  integer,
diffdbm_28  integer,
diffdbm_29  integer,
diffdbm_30  integer,
diffdbm_31  integer,
diffdbm_32  integer,
diffdbm_33  integer,
diffdbm_34  integer,
diffdbm_35  integer,
diffdbm_36  integer,
diffdbm_37  integer,
diffdbm_38  integer,
diffdbm_39  integer,
diffdbm_40  integer,
diffdbm_41  integer,
diffdbm_42  integer
);


create table tpl_mro_diff_day (
m_int_id  integer,
n_int_id  integer,
m_name  varchar2(128),
n_name  varchar2(128),
enodeb_name  varchar2(128),
related_enodeb  integer,
omc_id  integer,
enb_id  integer,
vendor_id  integer,
n_enb_id  integer,
m_eutrancell_id  varchar2(20),
m_celllocalid  integer,
n_eutrancell_id  varchar2(20),
n_celllocalid  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  int,
sum_level  int,
distince  number(38,8),
defined_ncell  integer,
error_flag  integer,
sc0diff0  integer,
sc1diff0  integer,
sc2diff0  integer,
sc3diff0  integer,
sc4diff0  integer,
sc5diff0  integer,
sc6diff0  integer,
sc7diff0  integer,
sc8diff0  integer,
sc9diff0  integer,
sc10diff0  integer,
sc0diff1  integer,
sc1diff1  integer,
sc2diff1  integer,
sc3diff1  integer,
sc4diff1  integer,
sc5diff1  integer,
sc6diff1  integer,
sc7diff1  integer,
sc8diff1  integer,
sc9diff1  integer,
sc10diff1  integer,
sc0diff2  integer,
sc1diff2  integer,
sc2diff2  integer,
sc3diff2  integer,
sc4diff2  integer,
sc5diff2  integer,
sc6diff2  integer,
sc7diff2  integer,
sc8diff2  integer,
sc9diff2  integer,
sc10diff2  integer,
sc0diff3  integer,
sc1diff3  integer,
sc2diff3  integer,
sc3diff3  integer,
sc4diff3  integer,
sc5diff3  integer,
sc6diff3  integer,
sc7diff3  integer,
sc8diff3  integer,
sc9diff3  integer,
sc10diff3  integer,
sc0diff4  integer,
sc1diff4  integer,
sc2diff4  integer,
sc3diff4  integer,
sc4diff4  integer,
sc5diff4  integer,
sc6diff4  integer,
sc7diff4  integer,
sc8diff4  integer,
sc9diff4  integer,
sc10diff4  integer,
sc0diff5  integer,
sc1diff5  integer,
sc2diff5  integer,
sc3diff5  integer,
sc4diff5  integer,
sc5diff5  integer,
sc6diff5  integer,
sc7diff5  integer,
sc8diff5  integer,
sc9diff5  integer,
sc10diff5  integer,
sc0diff6  integer,
sc1diff6  integer,
sc2diff6  integer,
sc3diff6  integer,
sc4diff6  integer,
sc5diff6  integer,
sc6diff6  integer,
sc7diff6  integer,
sc8diff6  integer,
sc9diff6  integer,
sc10diff6  integer,
sc0diff7  integer,
sc1diff7  integer,
sc2diff7  integer,
sc3diff7  integer,
sc4diff7  integer,
sc5diff7  integer,
sc6diff7  integer,
sc7diff7  integer,
sc8diff7  integer,
sc9diff7  integer,
sc10diff7  integer,
sc0diff8  integer,
sc1diff8  integer,
sc2diff8  integer,
sc3diff8  integer,
sc4diff8  integer,
sc5diff8  integer,
sc6diff8  integer,
sc7diff8  integer,
sc8diff8  integer,
sc9diff8  integer,
sc10diff8  integer,
sc0diff9  integer,
sc1diff9  integer,
sc2diff9  integer,
sc3diff9  integer,
sc4diff9  integer,
sc5diff9  integer,
sc6diff9  integer,
sc7diff9  integer,
sc8diff9  integer,
sc9diff9  integer,
sc10diff9  integer,
sc0diff10  integer,
sc1diff10  integer,
sc2diff10  integer,
sc3diff10  integer,
sc4diff10  integer,
sc5diff10  integer,
sc6diff10  integer,
sc7diff10  integer,
sc8diff10  integer,
sc9diff10  integer,
sc10diff10  integer,
ncrsrp0  integer,
ncrsrp1  integer,
ncrsrp2  integer,
ncrsrp3  integer,
ncrsrp4  integer,
ncrsrp5  integer,
ncrsrp6  integer,
ncrsrp7  integer,
ncrsrp8  integer,
ncrsrp9  integer,
ncrsrp10  integer,
total_num  integer,
nc_total_num  integer,
Sc_rsrp_sum     number(38,8)                  ,
Sc_rsrp_avg     number(38,8)                  ,
Nc_rsrp_sum     number(38,8)                  ,
Nc_rsrp_avg     number(38,8)                  ,
freq_type     integer                    ,
Sc0diff0_freq     integer                ,
Sc1diff0_freq     integer                ,
Sc2diff0_freq     integer                ,
Sc3diff0_freq     integer                ,
Sc4diff0_freq     integer                ,
Sc5diff0_freq     integer                ,
Sc6diff0_freq     integer                ,
Sc7diff0_freq     integer                ,
Sc8diff0_freq     integer                ,
Sc9diff0_freq     integer                ,
Sc10diff0_freq     integer                ,
Sc0diff1_freq     integer                ,
Sc1diff1_freq     integer                ,
Sc2diff1_freq     integer                ,
Sc3diff1_freq     integer                ,
Sc4diff1_freq     integer                ,
Sc5diff1_freq     integer                ,
Sc6diff1_freq     integer                ,
Sc7diff1_freq     integer                ,
Sc8diff1_freq     integer                ,
Sc9diff1_freq     integer                ,
Sc10diff1_freq     integer                ,
Sc0diff2_freq     integer                ,
Sc1diff2_freq     integer                ,
Sc2diff2_freq     integer                ,
Sc3diff2_freq     integer                ,
Sc4diff2_freq     integer                ,
Sc5diff2_freq     integer                ,
Sc6diff2_freq     integer                ,
Sc7diff2_freq     integer                ,
Sc8diff2_freq     integer                ,
Sc9diff2_freq     integer                ,
Sc10diff2_freq     integer                ,
Sc0diff3_freq     integer                ,
Sc1diff3_freq     integer                ,
Sc2diff3_freq     integer                ,
Sc3diff3_freq     integer                ,
Sc4diff3_freq     integer                ,
Sc5diff3_freq     integer                ,
Sc6diff3_freq     integer                ,
Sc7diff3_freq     integer                ,
Sc8diff3_freq     integer                ,
Sc9diff3_freq     integer                ,
Sc10diff3_freq     integer                ,
Sc0diff4_freq     integer                ,
Sc1diff4_freq     integer                ,
Sc2diff4_freq     integer                ,
Sc3diff4_freq     integer                ,
Sc4diff4_freq     integer                ,
Sc5diff4_freq     integer                ,
Sc6diff4_freq     integer                ,
Sc7diff4_freq     integer                ,
Sc8diff4_freq     integer                ,
Sc9diff4_freq     integer                ,
Sc10diff4_freq     integer                ,
Sc0diff5_freq     integer                ,
Sc1diff5_freq     integer                ,
Sc2diff5_freq     integer                ,
Sc3diff5_freq     integer                ,
Sc4diff5_freq     integer                ,
Sc5diff5_freq     integer                ,
Sc6diff5_freq     integer                ,
Sc7diff5_freq     integer                ,
Sc8diff5_freq     integer                ,
Sc9diff5_freq     integer                ,
Sc10diff5_freq     integer                ,
Sc0diff6_freq     integer                ,
Sc1diff6_freq     integer                ,
Sc2diff6_freq     integer                ,
Sc3diff6_freq     integer                ,
Sc4diff6_freq     integer                ,
Sc5diff6_freq     integer                ,
Sc6diff6_freq     integer                ,
Sc7diff6_freq     integer                ,
Sc8diff6_freq     integer                ,
Sc9diff6_freq     integer                ,
Sc10diff6_freq     integer                ,
Sc0diff7_freq     integer                ,
Sc1diff7_freq     integer                ,
Sc2diff7_freq     integer                ,
Sc3diff7_freq     integer                ,
Sc4diff7_freq     integer                ,
Sc5diff7_freq     integer                ,
Sc6diff7_freq     integer                ,
Sc7diff7_freq     integer                ,
Sc8diff7_freq     integer                ,
Sc9diff7_freq     integer                ,
Sc10diff7_freq     integer                ,
Sc0diff8_freq     integer                ,
Sc1diff8_freq     integer                ,
Sc2diff8_freq     integer                ,
Sc3diff8_freq     integer                ,
Sc4diff8_freq     integer                ,
Sc5diff8_freq     integer                ,
Sc6diff8_freq     integer                ,
Sc7diff8_freq     integer                ,
Sc8diff8_freq     integer                ,
Sc9diff8_freq     integer                ,
Sc10diff8_freq     integer                ,
Sc0diff9_freq     integer                ,
Sc1diff9_freq     integer                ,
Sc2diff9_freq     integer                ,
Sc3diff9_freq     integer                ,
Sc4diff9_freq     integer                ,
Sc5diff9_freq     integer                ,
Sc6diff9_freq     integer                ,
Sc7diff9_freq     integer                ,
Sc8diff9_freq     integer                ,
Sc9diff9_freq     integer                ,
Sc10diff9_freq     integer                ,
Sc0diff10_freq     integer                ,
Sc1diff10_freq     integer                ,
Sc2diff10_freq     integer                ,
Sc3diff10_freq     integer                ,
Sc4diff10_freq     integer                ,
Sc5diff10_freq     integer                ,
Sc6diff10_freq     integer                ,
Sc7diff10_freq     integer                ,
Sc8diff10_freq     integer                ,
Sc9diff10_freq     integer                ,
Sc10diff10_freq     integer                ,
ncrsrp0_freq     integer                ,
Ncrsrp1_freq     integer                ,
Ncrsrp2_freq     integer                ,
Ncrsrp3_freq     integer                ,
Ncrsrp4_freq     integer                ,
Ncrsrp5_freq     integer                ,
Ncrsrp6_freq     integer                ,
Ncrsrp7_freq     integer                ,
Ncrsrp8_freq     integer                ,
Ncrsrp9_freq     integer                ,
Ncrsrp10_freq     integer                ,
Total_num_freq     integer                ,
Nc_total_num_freq     integer            ,
Sc_rsrp_sum_freq     number(38,8)          ,
Sc_rsrp_avg_freq     number(38,8)          ,
Nc_rsrp_sum_freq     number(38,8)          ,
Nc_rsrp_avg_freq     number(38,8)          ,
freqband_type     integer                ,
Sc0diff0_freqband     integer            ,
Sc1diff0_freqband     integer            ,
Sc2diff0_freqband     integer            ,
Sc3diff0_freqband     integer            ,
Sc4diff0_freqband     integer            ,
Sc5diff0_freqband     integer            ,
Sc6diff0_freqband     integer            ,
Sc7diff0_freqband     integer            ,
Sc8diff0_freqband     integer            ,
Sc9diff0_freqband     integer            ,
Sc10diff0_freqband     integer            ,
Sc0diff1_freqband     integer            ,
Sc1diff1_freqband     integer            ,
Sc2diff1_freqband     integer            ,
Sc3diff1_freqband     integer            ,
Sc4diff1_freqband     integer            ,
Sc5diff1_freqband     integer            ,
Sc6diff1_freqband     integer            ,
Sc7diff1_freqband     integer            ,
Sc8diff1_freqband     integer            ,
Sc9diff1_freqband     integer            ,
Sc10diff1_freqband     integer            ,
Sc0diff2_freqband     integer            ,
Sc1diff2_freqband     integer            ,
Sc2diff2_freqband     integer            ,
Sc3diff2_freqband     integer            ,
Sc4diff2_freqband     integer            ,
Sc5diff2_freqband     integer            ,
Sc6diff2_freqband     integer            ,
Sc7diff2_freqband     integer            ,
Sc8diff2_freqband     integer            ,
Sc9diff2_freqband     integer            ,
Sc10diff2_freqband     integer            ,
Sc0diff3_freqband     integer            ,
Sc1diff3_freqband     integer            ,
Sc2diff3_freqband     integer            ,
Sc3diff3_freqband     integer            ,
Sc4diff3_freqband     integer            ,
Sc5diff3_freqband     integer            ,
Sc6diff3_freqband     integer            ,
Sc7diff3_freqband     integer            ,
Sc8diff3_freqband     integer            ,
Sc9diff3_freqband     integer            ,
Sc10diff3_freqband     integer            ,
Sc0diff4_freqband     integer            ,
Sc1diff4_freqband     integer            ,
Sc2diff4_freqband     integer            ,
Sc3diff4_freqband     integer            ,
Sc4diff4_freqband     integer            ,
Sc5diff4_freqband     integer            ,
Sc6diff4_freqband     integer            ,
Sc7diff4_freqband     integer            ,
Sc8diff4_freqband     integer            ,
Sc9diff4_freqband     integer            ,
Sc10diff4_freqband     integer            ,
Sc0diff5_freqband     integer            ,
Sc1diff5_freqband     integer            ,
Sc2diff5_freqband     integer            ,
Sc3diff5_freqband     integer            ,
Sc4diff5_freqband     integer            ,
Sc5diff5_freqband     integer            ,
Sc6diff5_freqband     integer            ,
Sc7diff5_freqband     integer            ,
Sc8diff5_freqband     integer            ,
Sc9diff5_freqband     integer            ,
Sc10diff5_freqband     integer            ,
Sc0diff6_freqband     integer            ,
Sc1diff6_freqband     integer            ,
Sc2diff6_freqband     integer            ,
Sc3diff6_freqband     integer            ,
Sc4diff6_freqband     integer            ,
Sc5diff6_freqband     integer            ,
Sc6diff6_freqband     integer            ,
Sc7diff6_freqband     integer            ,
Sc8diff6_freqband     integer            ,
Sc9diff6_freqband     integer            ,
Sc10diff6_freqband     integer            ,
Sc0diff7_freqband     integer            ,
Sc1diff7_freqband     integer            ,
Sc2diff7_freqband     integer            ,
Sc3diff7_freqband     integer            ,
Sc4diff7_freqband     integer            ,
Sc5diff7_freqband     integer            ,
Sc6diff7_freqband     integer            ,
Sc7diff7_freqband     integer            ,
Sc8diff7_freqband     integer            ,
Sc9diff7_freqband     integer            ,
Sc10diff7_freqband     integer            ,
Sc0diff8_freqband     integer            ,
Sc1diff8_freqband     integer            ,
Sc2diff8_freqband     integer            ,
Sc3diff8_freqband     integer            ,
Sc4diff8_freqband     integer            ,
Sc5diff8_freqband     integer            ,
Sc6diff8_freqband     integer            ,
Sc7diff8_freqband     integer            ,
Sc8diff8_freqband     integer            ,
Sc9diff8_freqband     integer            ,
Sc10diff8_freqband     integer            ,
Sc0diff9_freqband     integer            ,
Sc1diff9_freqband     integer            ,
Sc2diff9_freqband     integer            ,
Sc3diff9_freqband     integer            ,
Sc4diff9_freqband     integer            ,
Sc5diff9_freqband     integer            ,
Sc6diff9_freqband     integer            ,
Sc7diff9_freqband     integer            ,
Sc8diff9_freqband     integer            ,
Sc9diff9_freqband     integer            ,
Sc10diff9_freqband     integer            ,
Sc0diff10_freqband     integer            ,
Sc1diff10_freqband     integer            ,
Sc2diff10_freqband     integer            ,
Sc3diff10_freqband     integer            ,
Sc4diff10_freqband     integer            ,
Sc5diff10_freqband     integer            ,
Sc6diff10_freqband     integer            ,
Sc7diff10_freqband     integer            ,
Sc8diff10_freqband     integer            ,
Sc9diff10_freqband     integer            ,
Sc10diff10_freqband     integer            ,
ncrsrp0_freqband     integer            ,
Ncrsrp1_freqband     integer            ,
Ncrsrp2_freqband     integer            ,
Ncrsrp3_freqband     integer            ,
Ncrsrp4_freqband     integer            ,
Ncrsrp5_freqband     integer            ,
Ncrsrp6_freqband     integer            ,
Ncrsrp7_freqband     integer            ,
Ncrsrp8_freqband     integer            ,
Ncrsrp9_freqband     integer            ,
Ncrsrp10_freqband     integer            ,
Total_num_freqband     integer            ,
Nc_total_num_freqband     integer        ,
Sc_rsrp_sum_freqband     number(38,8)      ,
Sc_rsrp_avg_freqband     number(38,8)      ,
Nc_rsrp_sum_freqband     number(38,8)      ,
Nc_rsrp_avg_freqband     number(38,8)      
);


create table tpl_mro_diff_freq_day (
m_int_id  integer,
n_int_id  integer,
m_name  varchar2(128),
n_name  varchar2(128),
enodeb_name  varchar2(128),
related_enodeb  integer,
omc_id  integer,
enb_id  integer,
vendor_id  integer,
n_enb_id  integer,
m_eutrancell_id  varchar2(20),
m_celllocalid  integer,
n_eutrancell_id  varchar2(20),
n_celllocalid  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
distince  number(38,8),
defined_ncell  integer,
error_flag  integer,
freqtype  integer,
sc0diff0  integer,
sc1diff0  integer,
sc2diff0  integer,
sc3diff0  integer,
sc4diff0  integer,
sc5diff0  integer,
sc6diff0  integer,
sc7diff0  integer,
sc8diff0  integer,
sc9diff0  integer,
sc10diff0  integer,
sc0diff1  integer,
sc1diff1  integer,
sc2diff1  integer,
sc3diff1  integer,
sc4diff1  integer,
sc5diff1  integer,
sc6diff1  integer,
sc7diff1  integer,
sc8diff1  integer,
sc9diff1  integer,
sc10diff1  integer,
sc0diff2  integer,
sc1diff2  integer,
sc2diff2  integer,
sc3diff2  integer,
sc4diff2  integer,
sc5diff2  integer,
sc6diff2  integer,
sc7diff2  integer,
sc8diff2  integer,
sc9diff2  integer,
sc10diff2  integer,
sc0diff3  integer,
sc1diff3  integer,
sc2diff3  integer,
sc3diff3  integer,
sc4diff3  integer,
sc5diff3  integer,
sc6diff3  integer,
sc7diff3  integer,
sc8diff3  integer,
sc9diff3  integer,
sc10diff3  integer,
sc0diff4  integer,
sc1diff4  integer,
sc2diff4  integer,
sc3diff4  integer,
sc4diff4  integer,
sc5diff4  integer,
sc6diff4  integer,
sc7diff4  integer,
sc8diff4  integer,
sc9diff4  integer,
sc10diff4  integer,
sc0diff5  integer,
sc1diff5  integer,
sc2diff5  integer,
sc3diff5  integer,
sc4diff5  integer,
sc5diff5  integer,
sc6diff5  integer,
sc7diff5  integer,
sc8diff5  integer,
sc9diff5  integer,
sc10diff5  integer,
sc0diff6  integer,
sc1diff6  integer,
sc2diff6  integer,
sc3diff6  integer,
sc4diff6  integer,
sc5diff6  integer,
sc6diff6  integer,
sc7diff6  integer,
sc8diff6  integer,
sc9diff6  integer,
sc10diff6  integer,
sc0diff7  integer,
sc1diff7  integer,
sc2diff7  integer,
sc3diff7  integer,
sc4diff7  integer,
sc5diff7  integer,
sc6diff7  integer,
sc7diff7  integer,
sc8diff7  integer,
sc9diff7  integer,
sc10diff7  integer,
sc0diff8  integer,
sc1diff8  integer,
sc2diff8  integer,
sc3diff8  integer,
sc4diff8  integer,
sc5diff8  integer,
sc6diff8  integer,
sc7diff8  integer,
sc8diff8  integer,
sc9diff8  integer,
sc10diff8  integer,
sc0diff9  integer,
sc1diff9  integer,
sc2diff9  integer,
sc3diff9  integer,
sc4diff9  integer,
sc5diff9  integer,
sc6diff9  integer,
sc7diff9  integer,
sc8diff9  integer,
sc9diff9  integer,
sc10diff9  integer,
sc0diff10  integer,
sc1diff10  integer,
sc2diff10  integer,
sc3diff10  integer,
sc4diff10  integer,
sc5diff10  integer,
sc6diff10  integer,
sc7diff10  integer,
sc8diff10  integer,
sc9diff10  integer,
sc10diff10  integer,
ncrsrp0  integer,
ncrsrp1  integer,
ncrsrp2  integer,
ncrsrp3  integer,
ncrsrp4  integer,
ncrsrp5  integer,
ncrsrp6  integer,
ncrsrp7  integer,
ncrsrp8  integer,
ncrsrp9  integer,
total_num  integer,
nc_total_num  integer
);


create table tpl_mro_diff_freqband_day (
m_int_id  integer,
n_int_id  integer,
m_name  varchar2(128),
n_name  varchar2(128),
enodeb_name  varchar2(128),
related_enodeb  integer,
omc_id  integer,
enb_id  integer,
vendor_id  integer,
n_enb_id  integer,
m_eutrancell_id  varchar2(20),
m_celllocalid  integer,
n_eutrancell_id  varchar2(20),
n_celllocalid  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
distince  number(38,8),
defined_ncell  integer,
error_flag  integer,
freqtype  integer,
sc0diff0  integer,
sc1diff0  integer,
sc2diff0  integer,
sc3diff0  integer,
sc4diff0  integer,
sc5diff0  integer,
sc6diff0  integer,
sc7diff0  integer,
sc8diff0  integer,
sc9diff0  integer,
sc10diff0  integer,
sc0diff1  integer,
sc1diff1  integer,
sc2diff1  integer,
sc3diff1  integer,
sc4diff1  integer,
sc5diff1  integer,
sc6diff1  integer,
sc7diff1  integer,
sc8diff1  integer,
sc9diff1  integer,
sc10diff1  integer,
sc0diff2  integer,
sc1diff2  integer,
sc2diff2  integer,
sc3diff2  integer,
sc4diff2  integer,
sc5diff2  integer,
sc6diff2  integer,
sc7diff2  integer,
sc8diff2  integer,
sc9diff2  integer,
sc10diff2  integer,
sc0diff3  integer,
sc1diff3  integer,
sc2diff3  integer,
sc3diff3  integer,
sc4diff3  integer,
sc5diff3  integer,
sc6diff3  integer,
sc7diff3  integer,
sc8diff3  integer,
sc9diff3  integer,
sc10diff3  integer,
sc0diff4  integer,
sc1diff4  integer,
sc2diff4  integer,
sc3diff4  integer,
sc4diff4  integer,
sc5diff4  integer,
sc6diff4  integer,
sc7diff4  integer,
sc8diff4  integer,
sc9diff4  integer,
sc10diff4  integer,
sc0diff5  integer,
sc1diff5  integer,
sc2diff5  integer,
sc3diff5  integer,
sc4diff5  integer,
sc5diff5  integer,
sc6diff5  integer,
sc7diff5  integer,
sc8diff5  integer,
sc9diff5  integer,
sc10diff5  integer,
sc0diff6  integer,
sc1diff6  integer,
sc2diff6  integer,
sc3diff6  integer,
sc4diff6  integer,
sc5diff6  integer,
sc6diff6  integer,
sc7diff6  integer,
sc8diff6  integer,
sc9diff6  integer,
sc10diff6  integer,
sc0diff7  integer,
sc1diff7  integer,
sc2diff7  integer,
sc3diff7  integer,
sc4diff7  integer,
sc5diff7  integer,
sc6diff7  integer,
sc7diff7  integer,
sc8diff7  integer,
sc9diff7  integer,
sc10diff7  integer,
sc0diff8  integer,
sc1diff8  integer,
sc2diff8  integer,
sc3diff8  integer,
sc4diff8  integer,
sc5diff8  integer,
sc6diff8  integer,
sc7diff8  integer,
sc8diff8  integer,
sc9diff8  integer,
sc10diff8  integer,
sc0diff9  integer,
sc1diff9  integer,
sc2diff9  integer,
sc3diff9  integer,
sc4diff9  integer,
sc5diff9  integer,
sc6diff9  integer,
sc7diff9  integer,
sc8diff9  integer,
sc9diff9  integer,
sc10diff9  integer,
sc0diff10  integer,
sc1diff10  integer,
sc2diff10  integer,
sc3diff10  integer,
sc4diff10  integer,
sc5diff10  integer,
sc6diff10  integer,
sc7diff10  integer,
sc8diff10  integer,
sc9diff10  integer,
sc10diff10  integer,
ncrsrp0  integer,
ncrsrp1  integer,
ncrsrp2  integer,
ncrsrp3  integer,
ncrsrp4  integer,
ncrsrp5  integer,
ncrsrp6  integer,
ncrsrp7  integer,
ncrsrp8  integer,
ncrsrp9  integer,
total_num  integer,
nc_total_num  integer
);


create table tpl_mro_rsrprssi_day (
int_id  integer,
m_int_id  integer,
n_int_id  integer,
m_name  varchar2(128),
n_name  varchar2(128),
enodeb_name  varchar2(128),
related_enodeb  integer,
omc_id  integer,
enb_id  integer,
vendor_id  integer,
m_eutrancell_id  varchar2(20),
m_celllocalid  integer,
n_lac  integer,
n_ci  integer,
n_cgi  varchar2(64),
scan_start_time  date,
ncc  integer,
bcc  integer,
bcch  integer,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
distince  number(38,8),
defined_ncell  integer,
error_flag  integer,
sc0rssi0  integer,
sc0rssi1  integer,
sc0rssi2  integer,
sc0rssi3  integer,
sc0rssi4  integer,
sc0rssi5  integer,
sc0rssi6  integer,
sc0rssi7  integer,
sc0rssi8  integer,
sc0rssi9  integer,
sc1rssi0  integer,
sc1rssi1  integer,
sc1rssi2  integer,
sc1rssi3  integer,
sc1rssi4  integer,
sc1rssi5  integer,
sc1rssi6  integer,
sc1rssi7  integer,
sc1rssi8  integer,
sc1rssi9  integer,
sc2rssi0  integer,
sc2rssi1  integer,
sc2rssi2  integer,
sc2rssi3  integer,
sc2rssi4  integer,
sc2rssi5  integer,
sc2rssi6  integer,
sc2rssi7  integer,
sc2rssi8  integer,
sc2rssi9  integer,
sc3rssi0  integer,
sc3rssi1  integer,
sc3rssi2  integer,
sc3rssi3  integer,
sc3rssi4  integer,
sc3rssi5  integer,
sc3rssi6  integer,
sc3rssi7  integer,
sc3rssi8  integer,
sc3rssi9  integer,
sc4rssi0  integer,
sc4rssi1  integer,
sc4rssi2  integer,
sc4rssi3  integer,
sc4rssi4  integer,
sc4rssi5  integer,
sc4rssi6  integer,
sc4rssi7  integer,
sc4rssi8  integer,
sc4rssi9  integer,
sc5rssi0  integer,
sc5rssi1  integer,
sc5rssi2  integer,
sc5rssi3  integer,
sc5rssi4  integer,
sc5rssi5  integer,
sc5rssi6  integer,
sc5rssi7  integer,
sc5rssi8  integer,
sc5rssi9  integer,
sc6rssi0  integer,
sc6rssi1  integer,
sc6rssi2  integer,
sc6rssi3  integer,
sc6rssi4  integer,
sc6rssi5  integer,
sc6rssi6  integer,
sc6rssi7  integer,
sc6rssi8  integer,
sc6rssi9  integer,
sc7rssi0  integer,
sc7rssi1  integer,
sc7rssi2  integer,
sc7rssi3  integer,
sc7rssi4  integer,
sc7rssi5  integer,
sc7rssi6  integer,
sc7rssi7  integer,
sc7rssi8  integer,
sc7rssi9  integer,
sc8rssi0  integer,
sc8rssi1  integer,
sc8rssi2  integer,
sc8rssi3  integer,
sc8rssi4  integer,
sc8rssi5  integer,
sc8rssi6  integer,
sc8rssi7  integer,
sc8rssi8  integer,
sc8rssi9  integer,
sc9rssi0  integer,
sc9rssi1  integer,
sc9rssi2  integer,
sc9rssi3  integer,
sc9rssi4  integer,
sc9rssi5  integer,
sc9rssi6  integer,
sc9rssi7  integer,
sc9rssi8  integer,
sc9rssi9  integer,
sc10rssi0  integer,
sc10rssi1  integer,
sc10rssi2  integer,
sc10rssi3  integer,
sc10rssi4  integer,
sc10rssi5  integer,
sc10rssi6  integer,
sc10rssi7  integer,
sc10rssi8  integer,
sc10rssi9  integer,
ncrssi0  integer,
ncrssi1  integer,
ncrssi2  integer,
ncrssi3  integer,
ncrssi4  integer,
ncrssi5  integer,
ncrssi6  integer,
ncrssi7  integer,
ncrssi8  integer,
ncrssi9  integer,
total_num  integer,
nc_total_num  integer,
total_num_85  integer,
total_num_90  integer,
total_num_95  integer,
rsrp_sum    number(38,8)  ,
rssi_sum    number(38,8)  
);


create table tpl_mro_numofadj_eutr_day (
int_id  integer,
vendor_id  integer,
name  varchar2(128),
related_enodeb  integer,
enodeb_name  varchar2(128),
enb_id  integer,
eutrancell_id  varchar2(20),
celllocalid  integer,
omc_id  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
num0diff0  integer,
num1diff0  integer,
num2diff0  integer,
num3diff0  integer,
num4diff0  integer,
num5diff0  integer,
num6diff0  integer,
num7diff0  integer,
num8diff0  integer,
num9diff0  integer,
num10diff0  integer,
num11diff0  integer,
num12diff0  integer,
num13diff0  integer,
num14diff0  integer,
num15diff0  integer,
num16diff0  integer,
num17diff0  integer,
num18diff0  integer,
num19diff0  integer,
num20diff0  integer,
num0diff1  integer,
num1diff1  integer,
num2diff1  integer,
num3diff1  integer,
num4diff1  integer,
num5diff1  integer,
num6diff1  integer,
num7diff1  integer,
num8diff1  integer,
num9diff1  integer,
num10diff1  integer,
num11diff1  integer,
num12diff1  integer,
num13diff1  integer,
num14diff1  integer,
num15diff1  integer,
num16diff1  integer,
num17diff1  integer,
num18diff1  integer,
num19diff1  integer,
num20diff1  integer,
total_num  integer,
freq_type    integer            ,
num0diff0_freq    integer    ,
num1diff0_freq    integer    ,
num2diff0_freq    integer    ,
num3diff0_freq    integer    ,
num4diff0_freq    integer    ,
num5diff0_freq    integer    ,
num6diff0_freq    integer    ,
num7diff0_freq    integer    ,
num8diff0_freq    integer    ,
num9diff0_freq    integer    ,
num10diff0_freq    integer    ,
num11diff0_freq    integer    ,
num12diff0_freq    integer    ,
num13diff0_freq    integer    ,
num14diff0_freq    integer    ,
num15diff0_freq    integer    ,
num16diff0_freq    integer    ,
num17diff0_freq    integer    ,
num18diff0_freq    integer    ,
num19diff0_freq    integer    ,
num20diff0_freq    integer    ,
num0diff1_freq    integer    ,
num1diff1_freq    integer    ,
num2diff1_freq    integer    ,
num3diff1_freq    integer    ,
num4diff1_freq    integer    ,
num5diff1_freq    integer    ,
num6diff1_freq    integer    ,
num7diff1_freq    integer    ,
num8diff1_freq    integer    ,
num9diff1_freq    integer    ,
num10diff1_freq    integer    ,
num11diff1_freq    integer    ,
num12diff1_freq    integer    ,
num13diff1_freq    integer    ,
num14diff1_freq    integer    ,
num15diff1_freq    integer    ,
num16diff1_freq    integer    ,
num17diff1_freq    integer    ,
num18diff1_freq    integer    ,
num19diff1_freq    integer    ,
num20diff1_freq    integer    ,
Total_num_freq    integer    ,
freqband_type    integer        ,
num0diff0_freqband    integer,
num1diff0_freqband    integer,
num2diff0_freqband    integer,
num3diff0_freqband    integer,
num4diff0_freqband    integer,
num5diff0_freqband    integer,
num6diff0_freqband    integer,
num7diff0_freqband    integer,
num8diff0_freqband    integer,
num9diff0_freqband    integer,
num10diff0_freqband    integer,
num11diff0_freqband    integer,
num12diff0_freqband    integer,
num13diff0_freqband    integer,
num14diff0_freqband    integer,
num15diff0_freqband    integer,
num16diff0_freqband    integer,
num17diff0_freqband    integer,
num18diff0_freqband    integer,
num19diff0_freqband    integer,
num20diff0_freqband    integer,
num0diff1_freqband    integer,
num1diff1_freqband    integer,
num2diff1_freqband    integer,
num3diff1_freqband    integer,
num4diff1_freqband    integer,
num5diff1_freqband    integer,
num6diff1_freqband    integer,
num7diff1_freqband    integer,
num8diff1_freqband    integer,
num9diff1_freqband    integer,
num10diff1_freqband    integer,
num11diff1_freqband    integer,
num12diff1_freqband    integer,
num13diff1_freqband    integer,
num14diff1_freqband    integer,
num15diff1_freqband    integer,
num16diff1_freqband    integer,
num17diff1_freqband    integer,
num18diff1_freqband    integer,
num19diff1_freqband    integer,
num20diff1_freqband    integer,
Total_num_freqband    integer
);


create table tpl_mro_numofadj_freq_day (
int_id  integer,
vendor_id  integer,
name  varchar2(128),
related_enodeb  integer,
enodeb_name  varchar2(128),
enb_id  integer,
eutrancell_id  varchar2(20),
celllocalid  integer,
omc_id  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
freqtype  integer,
num0diff0  integer,
num1diff0  integer,
num2diff0  integer,
num3diff0  integer,
num4diff0  integer,
num5diff0  integer,
num6diff0  integer,
num7diff0  integer,
num8diff0  integer,
num9diff0  integer,
num10diff0  integer,
num11diff0  integer,
num12diff0  integer,
num13diff0  integer,
num14diff0  integer,
num15diff0  integer,
num16diff0  integer,
num17diff0  integer,
num18diff0  integer,
num19diff0  integer,
num20diff0  integer,
num0diff1  integer,
num1diff1  integer,
num2diff1  integer,
num3diff1  integer,
num4diff1  integer,
num5diff1  integer,
num6diff1  integer,
num7diff1  integer,
num8diff1  integer,
num9diff1  integer,
num10diff1  integer,
num11diff1  integer,
num12diff1  integer,
num13diff1  integer,
num14diff1  integer,
num15diff1  integer,
num16diff1  integer,
num17diff1  integer,
num18diff1  integer,
num19diff1  integer,
num20diff1  integer,
total_num  integer
);


create table tpl_mro_numofadj_freqband_day (
int_id  integer,
vendor_id  integer,
name  varchar2(128),
related_enodeb  integer,
enodeb_name  varchar2(128),
enb_id  integer,
eutrancell_id  varchar2(20),
celllocalid  integer,
omc_id  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
freqtype  integer,
num0diff0  integer,
num1diff0  integer,
num2diff0  integer,
num3diff0  integer,
num4diff0  integer,
num5diff0  integer,
num6diff0  integer,
num7diff0  integer,
num8diff0  integer,
num9diff0  integer,
num10diff0  integer,
num11diff0  integer,
num12diff0  integer,
num13diff0  integer,
num14diff0  integer,
num15diff0  integer,
num16diff0  integer,
num17diff0  integer,
num18diff0  integer,
num19diff0  integer,
num20diff0  integer,
num0diff1  integer,
num1diff1  integer,
num2diff1  integer,
num3diff1  integer,
num4diff1  integer,
num5diff1  integer,
num6diff1  integer,
num7diff1  integer,
num8diff1  integer,
num9diff1  integer,
num10diff1  integer,
num11diff1  integer,
num12diff1  integer,
num13diff1  integer,
num14diff1  integer,
num15diff1  integer,
num16diff1  integer,
num17diff1  integer,
num18diff1  integer,
num19diff1  integer,
num20diff1  integer,
total_num  integer
);


create table tpl_mro_rsrp_day (
int_id  integer,
omc_id  integer,
vendor_id  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
related_enodeb  integer,
enodeb_name  varchar2(128),
enodeb_id  integer,
eutrancell_id  integer,
rsrp_0  integer,
rsrp_1  integer,
rsrp_2  integer,
rsrp_3  integer,
rsrp_4  integer,
rsrp_5  integer,
rsrp_6  integer,
rsrp_7  integer,
rsrp_8  integer,
rsrp_9  integer,
rsrp_10  integer,
rsrp_11  integer,
rsrp_sum  number(38,8),
rsrp_count  integer,
rsrp_avg  number(38,8),
rsrp_lt_f110  integer,
rsrp_lt_f113  integer,
rsrp_lt_f115  integer,
un_maxrsrp_0  integer,
un_maxrsrp_1  integer,
un_maxrsrp_2  integer,
un_maxrsrp_3  integer,
un_maxrsrp_4  integer,
un_maxrsrp_5  integer,
un_maxrsrp_6  integer,
un_maxrsrp_7  integer,
un_maxrsrp_8  integer,
un_maxrsrp_9  integer,
un_maxrsrp_10  integer,
un_maxrsrp_11  integer,
un_maxrsrp_sum  number(38,8),
un_maxrsrp_count  integer,
un_maxrsrp_avg  number(38,8),
un_maxrsrp_lt_f110  integer,
un_maxrsrp_f113  integer,
un_maxrsrp_f115  integer,
te_maxrsrp_0  integer,
te_maxrsrp_1  integer,
te_maxrsrp_2  integer,
te_maxrsrp_3  integer,
te_maxrsrp_4  integer,
te_maxrsrp_5  integer,
te_maxrsrp_6  integer,
te_maxrsrp_7  integer,
te_maxrsrp_8  integer,
te_maxrsrp_9  integer,
te_maxrsrp_10  integer,
te_maxrsrp_11  integer,
te_maxrsrp_sum  number(38,8),
te_maxrsrp_count  integer,
te_maxrsrp_avg  number(38,8),
te_maxrsrp_lt_f110  integer,
te_maxrsrp_f113  integer,
te_maxrsrp_f115  integer,
inter_maxrsrp_0  integer,
inter_maxrsrp_1  integer,
inter_maxrsrp_2  integer,
inter_maxrsrp_3  integer,
inter_maxrsrp_4  integer,
inter_maxrsrp_5  integer,
inter_maxrsrp_6  integer,
inter_maxrsrp_7  integer,
inter_maxrsrp_8  integer,
inter_maxrsrp_9  integer,
inter_maxrsrp_10  integer,
inter_maxrsrp_11  integer,
inter_maxrsrp_sum  number(38,8),
inter_maxrsrp_count  integer,
inter_maxrsrp_avg  number(38,8),
inter_maxrsrp_lt_f110  integer,
inter_maxrsrp_f113  integer,
inter_maxrsrp_f115  integer
);


create table tpl_mro_sinr_rsrp_day (
int_id  integer,
omc_id  integer,
vendor_id  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
related_enodeb  integer,
enodeb_name  varchar2(128),
enodeb_id  integer,
eutrancell_id  integer,
sinr  integer,
rsrp_00  integer,
rsrp_01  integer,
rsrp_02  integer,
rsrp_03  integer,
rsrp_04  integer,
rsrp_05  integer,
rsrp_06  integer,
rsrp_07  integer,
rsrp_08  integer,
rsrp_09  integer,
rsrp_10  integer,
rsrp_11  integer,
rsrp_12  integer,
rsrp_13  integer,
rsrp_14  integer,
rsrp_15  integer,
rsrp_16  integer,
rsrp_17  integer,
rsrp_18  integer,
rsrp_19  integer,
rsrp_20  integer,
rsrp_21  integer,
rsrp_22  integer,
rsrp_23  integer,
rsrp_24  integer,
rsrp_25  integer,
rsrp_26  integer,
rsrp_27  integer,
rsrp_28  integer,
rsrp_29  integer,
rsrp_30  integer,
rsrp_31  integer,
rsrp_32  integer,
rsrp_33  integer,
rsrp_34  integer,
rsrp_35  integer,
rsrp_36  integer,
rsrp_37  integer,
rsrp_38  integer,
rsrp_39  integer,
rsrp_40  integer,
rsrp_41  integer,
rsrp_42  integer,
rsrp_43  integer,
rsrp_44  integer,
rsrp_45  integer,
rsrp_46  integer,
rsrp_47  integer,
rsrp_sum  number(38,8),
rsrp_count  integer
);


create table tpl_mro_rip_day (
int_id  integer,
omc_id  integer,
vendor_id  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
related_enodeb  integer,
enodeb_name  varchar2(128),
enodeb_id  integer,
eutrancell_id  integer,
rip_00  integer,
rip_01  integer,
rip_02  integer,
rip_03  integer,
rip_04  integer,
rip_05  integer,
rip_06  integer,
rip_07  integer,
rip_08  integer,
rip_09  integer,
rip_10  integer,
rip_11  integer,
rip_12  integer,
rip_13  integer,
rip_14  integer,
rip_15  integer,
rip_16  integer,
rip_17  integer,
rip_18  integer,
rip_19  integer,
rip_20  integer,
rip_21  integer,
rip_22  integer,
rip_23  integer,
rip_24  integer,
rip_25  integer,
rip_26  integer,
rip_27  integer,
rip_28  integer,
rip_29  integer,
rip_30  integer,
rip_31  integer,
rip_32  integer,
rip_33  integer,
rip_34  integer,
rip_35  integer,
rip_36  integer,
rip_37  integer,
rip_38  integer,
rip_39  integer,
rip_40  integer,
rip_41  integer,
rip_42  integer,
rip_43  integer,
rip_44  integer,
rip_45  integer,
rip_46  integer,
rip_47  integer,
rip_48  integer,
rip_49  integer,
rip_50  integer,
rip_51  integer,
rip_52  integer,
rip_53  integer,
rip_54  integer,
rip_55  integer,
rip_56  integer,
rip_57  integer,
rip_58  integer,
rip_59  integer,
rip_60  integer,
rip_61  integer,
rip_62  integer,
rip_63  integer,
rip_64  integer,
rip_65  integer,
rip_66  integer,
rip_67  integer,
rip_68  integer,
rip_69  integer,
rip_70  integer,
rip_71  integer,
rip_72  integer,
rip_73  integer,
rip_74  integer,
rip_75  integer,
rip_76  integer,
rip_77  integer,
rip_78  integer,
rip_79  integer,
rip_80  integer,
rip_81  integer,
rip_82  integer,
rip_83  integer,
rip_84  integer,
rip_85  integer,
rip_86  integer,
rip_87  integer,
rip_88  integer,
rip_89  integer,
rip_90  integer,
rip_91  integer,
rip_92  integer,
rip_93  integer,
rip_94  integer,
rip_95  integer,
rip_96  integer,
rip_97  integer,
rip_98  integer,
rip_99  integer,
rip_100  integer,
rip_101  integer,
rip_102  integer,
rip_103  integer,
rip_sum  number(38,8),
rip_count  integer
);


create table tpl_mro_sinrul_day (
int_id  integer,
omc_id  integer,
vendor_id  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
related_enodeb  integer,
enodeb_name  varchar2(128),
enodeb_id  integer,
eutrancell_id  integer,
sinrul_00  integer,
sinrul_01  integer,
sinrul_02  integer,
sinrul_03  integer,
sinrul_04  integer,
sinrul_05  integer,
sinrul_06  integer,
sinrul_07  integer,
sinrul_08  integer,
sinrul_09  integer,
sinrul_10  integer,
sinrul_11  integer,
sinrul_12  integer,
sinrul_13  integer,
sinrul_14  integer,
sinrul_15  integer,
sinrul_16  integer,
sinrul_17  integer,
sinrul_18  integer,
sinrul_19  integer,
sinrul_20  integer,
sinrul_21  integer,
sinrul_22  integer,
sinrul_23  integer,
sinrul_24  integer,
sinrul_25  integer,
sinrul_26  integer,
sinrul_27  integer,
sinrul_28  integer,
sinrul_29  integer,
sinrul_30  integer,
sinrul_31  integer,
sinrul_32  integer,
sinrul_33  integer,
sinrul_34  integer,
sinrul_35  integer,
sinrul_36  integer,
sinrul_sum  number(38,8),
sinrul_count  integer
);


create table tpl_mro_adjtdl_day (
int_id  integer,
omc_id  integer,
vendor_id  integer,
m_name  varchar2(128),
m_int_id  integer,
m_celllocalid  integer,
enodeb_name  varchar2(128),
related_enodeb  integer,
n_name  varchar2(128),
n_int_id  integer,
n_celllocalid  integer,
enb_id  integer,
n_enb_id  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
distince  number(38,8),
defined_ncell  integer,
error_flag  integer,
diff0  integer,
diff1  integer,
diff2  integer,
diff3  integer,
diff4  integer,
diff5  integer,
diff6  integer,
diff7  integer,
diff8  integer,
diff9  integer,
diff10  integer,
total_num  integer,
nc_total_num  integer,
nc_sc_overf6  integer,
nc_sc_overf3  integer,
nc_sc_overf12  integer,
nc_sc_overf6_rate  number(38,8),
ncrsrp0  integer,
ncrsrp1  integer,
ncrsrp2  integer,
ncrsrp3  integer,
ncrsrp4  integer,
ncrsrp5  integer,
ncrsrp6  integer,
ncrsrp7  integer,
ncrsrp8  integer,
ncrsrp9  integer,
ncrsrp10  integer,
Sc_rsrp_sum     number(38,8)                ,
Nc_rsrp_sum     number(38,8)                ,
Sc_rsrp_avg     number(38,8)                ,
Nc_rsrp_avg     number(38,8)                ,
freq_type     integer                      ,
diff0_freq     integer                      ,
diff1_freq     integer                      ,
diff2_freq     integer                      ,
diff3_freq     integer                      ,
diff4_freq     integer                      ,
diff5_freq     integer                      ,
diff6_freq     integer                      ,
diff7_freq     integer                      ,
diff8_freq     integer                      ,
diff9_freq     integer                      ,
diff10_freq     integer                  ,
Total_num_freq     integer                  ,
Nc_total_num_freq     integer              ,
Nc_sc_overf6_freq     number(38,8)            ,
Nc_sc_overf3_freq     number(38,8)            ,
Nc_sc_overf12_freq     number(38,8)            ,
Nc_sc_overf6_rate_freq     number(38,8)        ,
ncrsrp0_freq     integer                  ,
Ncrsrp1_freq     integer                  ,
Ncrsrp2_freq     integer                  ,
Ncrsrp3_freq     integer                  ,
Ncrsrp4_freq     integer                  ,
Ncrsrp5_freq     integer                  ,
Ncrsrp6_freq     integer                  ,
Ncrsrp7_freq     integer                  ,
Ncrsrp8_freq     integer                  ,
Ncrsrp9_freq     integer                  ,
Ncrsrp10_freq     integer                  ,
Sc_rsrp_sum_freq     number(38,8)            ,
Nc_rsrp_sum_freq     number(38,8)            ,
Sc_rsrp_avg_freq     number(38,8)            ,
Nc_rsrp_avg_freq     number(38,8)            ,
freqband_type     integer                  ,
diff0_freqband     integer                  ,
diff1_freqband     integer                  ,
diff2_freqband     integer                  ,
diff3_freqband     integer                  ,
diff4_freqband     integer                  ,
diff5_freqband     integer                  ,
diff6_freqband     integer                  ,
diff7_freqband     integer                  ,
diff8_freqband     integer                  ,
diff9_freqband     integer                  ,
diff10_freqband     integer              ,
Total_num_freqband     integer              ,
Nc_total_num_freqband     integer          ,
Nc_sc_overf6_freqband     number(38,8)        ,
Nc_sc_overf3_freqband     number(38,8)        ,
Nc_sc_overf12_freqband     number(38,8)        ,
Nc_sc_overf6_rate_freqband     number(38,8)    ,
ncrsrp0_freqband     integer              ,
Ncrsrp1_freqband     integer              ,
Ncrsrp2_freqband     integer              ,
Ncrsrp3_freqband     integer              ,
Ncrsrp4_freqband     integer              ,
Ncrsrp5_freqband     integer              ,
Ncrsrp6_freqband     integer              ,
Ncrsrp7_freqband     integer              ,
Ncrsrp8_freqband     integer              ,
Ncrsrp9_freqband     integer              ,
Ncrsrp10_freqband     integer              ,
Sc_rsrp_sum_freqband     number(38,8)        ,
Nc_rsrp_sum_freqband     number(38,8)        ,
Sc_rsrp_avg_freqband     number(38,8)        ,
Nc_rsrp_avg_freqband     number(38,8)        
);


create table tpl_mro_adjtdl_freq_day (
int_id  integer,
omc_id  integer,
vendor_id  integer,
m_name  varchar2(128),
m_int_id  integer,
m_celllocalid  integer,
enodeb_name  varchar2(128),
related_enodeb  integer,
n_name  varchar2(128),
n_int_id  integer,
n_celllocalid  integer,
enb_id  integer,
n_enb_id  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
distince  number(38,8),
defined_ncell  integer,
error_flag  integer,
diff0  integer,
diff1  integer,
diff2  integer,
diff3  integer,
diff4  integer,
diff5  integer,
diff6  integer,
diff7  integer,
diff8  integer,
diff9  integer,
diff10  integer,
freqtype  integer,
total_num  integer,
nc_total_num  integer,
nc_sc_overf6  integer,
nc_sc_overf3  integer,
nc_sc_overf12  integer,
nc_sc_overf6_rate  number(38,8),
ncrsrp0  integer,
ncrsrp1  integer,
ncrsrp2  integer,
ncrsrp3  integer,
ncrsrp4  integer,
ncrsrp5  integer,
ncrsrp6  integer,
ncrsrp7  integer,
ncrsrp8  integer,
ncrsrp9  integer,
ncrsrp10  integer
);


create table tpl_mro_adjtdl_freqband_day (
int_id  integer,
omc_id  integer,
vendor_id  integer,
m_name  varchar2(128),
m_int_id  integer,
m_celllocalid  integer,
enodeb_name  varchar2(128),
related_enodeb  integer,
n_name  varchar2(128),
n_int_id  integer,
n_celllocalid  integer,
enb_id  integer,
n_enb_id  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
distince  number(38,8),
defined_ncell  integer,
error_flag  integer,
diff0  integer,
diff1  integer,
diff2  integer,
diff3  integer,
diff4  integer,
diff5  integer,
diff6  integer,
diff7  integer,
diff8  integer,
diff9  integer,
diff10  integer,
freqtype  integer,
total_num  integer,
nc_total_num  integer,
nc_sc_overf6  integer,
nc_sc_overf3  integer,
nc_sc_overf12  integer,
nc_sc_overf6_rate  number(38,8),
ncrsrp0  integer,
ncrsrp1  integer,
ncrsrp2  integer,
ncrsrp3  integer,
ncrsrp4  integer,
ncrsrp5  integer,
ncrsrp6  integer,
ncrsrp7  integer,
ncrsrp8  integer,
ncrsrp9  integer,
ncrsrp10  integer
);


create table tpl_mro_adjtdl_gsm_day (
int_id  integer,
omc_id  integer,
vendor_id  integer,
m_name  varchar2(128),
m_int_id  integer,
m_celllocalid  integer,
enodeb_name  varchar2(128),
related_enodeb  integer,
n_name  varchar2(128),
n_int_id  integer,
n_lac  integer,
n_ci  integer,
n_cgi  varchar2(64),
ncc  integer,
bcc  integer,
bcch  integer,
enb_id  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
distince  number(38,8),
defined_ncell  integer,
error_flag  integer,
rssiov85_rsrpls85  integer,
rssiov90_rsrpls90  integer,
rssiov95_rsrpls95  integer,
total_num  integer,
nc_total_num  integer,
total_num_85  integer,
total_num_90  integer,
total_num_95  integer,
correlation_85  number(38,8),
correlation_90  number(38,8),
correlation_95  number(38,8),
gsm_ave_rsrp_sc  number(38,8),
gsm_ave_rsrp_sc_all  number(38,8),
ncrssi0  integer,
ncrssi1  integer,
ncrssi2  integer,
ncrssi3  integer,
ncrssi4  integer,
ncrssi5  integer,
ncrssi6  integer,
ncrssi7  integer,
ncrssi8  integer,
ncrssi9  integer
);


create table tpl_mro_pol_adj_day (
int_id  integer,
omc_id  integer,
vendor_id  integer,
m_name  varchar2(128),
m_int_id  integer,
m_celllocalid  integer,
enodeb_name  varchar2(128),
related_enodeb  integer,
n_name  varchar2(128),
n_int_id  integer,
n_celllocalid  integer,
enb_id  integer,
n_enb_id  integer,
scan_start_time  date,
scan_stop_time  date,
scearfcn  integer,
scpci  integer,
ncearfcn  integer,
ncpci  integer,
insert_time  date,
ne_type  integer,
sum_level  integer,
city_id  integer,
region_id  integer,
defined_ncell  integer,
tdl_ave_rscp_sc  number(38,8),
tdl_ave_rsrp_sc_all  number(38,8),
tdl_tim  integer,
tdl_ave_rscp_nc  number(38,8),
tdl_tim_alone  integer,
nrsrp_threshold_count  integer,
tdl_tim_max  integer,
tdl_tim_ncrsrp  integer,
tdl_tim1  integer,
tdl_tim2  integer,
tdl_tim3  integer,
tdl_tim4  integer,
tdl_tim5  integer,
tdl_tim6  integer,
tdl_tim1_ncrsrp  number(38,8),
tdl_tim2_ncrsrp  number(38,8),
tdl_tim3_ncrsrp  number(38,8),
tdl_tim4_ncrsrp  number(38,8),
tdl_tim5_ncrsrp  number(38,8),
tdl_tim6_ncrsrp  number(38,8),
overlap_count1  integer,
overlap_count2  integer,
tdl_ave_rscp_nc_overlap_condi1  number(38,8),
tdl_tim1_overlap_condi1  integer,
tdl_tim2_overlap_condi1  integer,
tdl_tim3_overlap_condi1  integer,
tdl_tim4_overlap_condi1  integer,
tdl_tim5_overlap_condi1  integer,
tdl_tim6_overlap_condi1  integer,
tdl_tim1_overlap_condi1_ncrsrp  integer,
tdl_tim2_overlap_condi1_ncrsrp  integer,
tdl_tim3_overlap_condi1_ncrsrp  integer,
tdl_tim4_overlap_condi1_ncrsrp  integer,
tdl_tim5_overlap_condi1_ncrsrp  integer,
tdl_tim6_overlap_condi1_ncrsrp  integer,
tdl_ave_rscp_nc_overlap_condi2  number(38,8),
tdl_tim1_overlap_condi2  integer,
tdl_tim2_overlap_condi2  integer,
tdl_tim3_overlap_condi2  integer,
tdl_tim4_overlap_condi2  integer,
tdl_tim5_overlap_condi2  integer,
tdl_tim6_overlap_condi2  integer,
tdl_tim1_overlap_condi2_ncrsrp  integer,
tdl_tim2_overlap_condi2_ncrsrp  integer,
tdl_tim3_overlap_condi2_ncrsrp  integer,
tdl_tim4_overlap_condi2_ncrsrp  number(38,8),
tdl_tim5_overlap_condi2_ncrsrp  number(38,8),
tdl_tim6_overlap_condi2_ncrsrp  number(38,8),
scrsrp_sum  number(38,8),
total_num  integer,
rsrpdiff_abssum  number(38,8),
rsrpdiff_absavg  number(38,8),
ncrsrp_0  integer,
ncrsrp_1  integer,
ncrsrp_2  integer,
ncrsrp_3  integer,
ncrsrp_4  integer,
ncrsrp_5  integer,
ncrsrp_6  integer,
ncrsrp_7  integer,
ncrsrp_8  integer,
ncrsrp_9  integer,
ncrsrp_10  integer,
ncrsrp_11  integer,
ncrsrp_12  integer,
ncrsrp_13  integer,
ncrsrp_14  integer,
ncrsrp_15  integer,
ncrsrp_16  integer,
ncrsrp_17  integer,
ncrsrp_18  integer,
ncrsrp_19  integer,
ncrsrp_20  integer,
ncrsrp_21  integer,
ncrsrp_22  integer,
ncrsrp_23  integer,
ncrsrp_24  integer,
ncrsrp_25  integer,
ncrsrp_26  integer,
ncrsrp_27  integer,
ncrsrp_28  integer,
ncrsrp_29  integer,
ncrsrp_30  integer,
ncrsrp_31  integer,
ncrsrp_32  integer,
ncrsrp_33  integer,
ncrsrp_34  integer,
ncrsrp_35  integer,
ncrsrp_36  integer,
ncrsrp_37  integer,
ncrsrp_38  integer,
ncrsrp_39  integer,
ncrsrp_40  integer,
ncrsrp_41  integer,
ncrsrp_42  integer,
ncrsrp_43  integer,
ncrsrp_44  integer,
ncrsrp_45  integer,
ncrsrp_46  integer,
ncrsrp_47  integer,
ncrsrp_48  integer,
ncrsrp_49  integer,
ncrsrp_50  integer,
ncrsrp_51  integer,
ncrsrp_52  integer,
ncrsrp_53  integer,
ncrsrp_54  integer,
ncrsrp_55  integer,
ncrsrp_56  integer,
ncrsrp_57  integer,
ncrsrp_58  integer,
ncrsrp_59  integer,
ncrsrp_60  integer,
ncrsrp_61  integer,
ncrsrp_62  integer,
ncrsrp_63  integer,
ncrsrp_64  integer,
ncrsrp_65  integer,
ncrsrp_66  integer,
ncrsrp_67  integer,
ncrsrp_68  integer,
ncrsrp_69  integer,
ncrsrp_70  integer,
ncrsrp_71  integer,
ncrsrp_72  integer,
ncrsrp_73  integer,
ncrsrp_74  integer,
ncrsrp_75  integer,
ncrsrp_76  integer,
ncrsrp_77  integer,
ncrsrp_78  integer,
ncrsrp_79  integer,
ncrsrp_80  integer,
ncrsrp_81  integer,
ncrsrp_82  integer,
ncrsrp_83  integer,
ncrsrp_84  integer,
ncrsrp_85  integer,
ncrsrp_86  integer,
ncrsrp_87  integer,
ncrsrp_88  integer,
ncrsrp_89  integer,
ncrsrp_90  integer,
ncrsrp_91  integer,
ncrsrp_92  integer,
ncrsrp_93  integer,
ncrsrp_94  integer,
ncrsrp_95  integer,
ncrsrp_96  integer,
ncrsrp_97  integer,
ncrsrp_sum  number(38,8),
ncrsrp_count  integer,
nc_netype  integer
);


create table tdl_mro_aoa (
int_id   integer,
omc_id  integer,
vendor_id  integer,
scan_start_time  date,
scan_stop_time  date,
insert_time  date,
ne_type  integer,
sum_level  integer,
related_enodeb  integer,
enodeb_name  varchar2(128),
enodeb_id  integer,
eutrancell_id  integer,
aoa_000  integer,
aoa_001  integer,
aoa_002  integer,
aoa_003  integer,
aoa_004  integer,
aoa_005  integer,
aoa_006  integer,
aoa_007  integer,
aoa_008  integer,
aoa_009  integer,
aoa_010  integer,
aoa_011  integer,
aoa_012  integer,
aoa_013  integer,
aoa_014  integer,
aoa_015  integer,
aoa_016  integer,
aoa_017  integer,
aoa_018  integer,
aoa_019  integer,
aoa_020  integer,
aoa_021  integer,
aoa_022  integer,
aoa_023  integer,
aoa_024  integer,
aoa_025  integer,
aoa_026  integer,
aoa_027  integer,
aoa_028  integer,
aoa_029  integer,
aoa_030  integer,
aoa_031  integer,
aoa_032  integer,
aoa_033  integer,
aoa_034  integer,
aoa_035  integer,
aoa_036  integer,
aoa_037  integer,
aoa_038  integer,
aoa_039  integer,
aoa_040  integer,
aoa_041  integer,
aoa_042  integer,
aoa_043  integer,
aoa_044  integer,
aoa_045  integer,
aoa_046  integer,
aoa_047  integer,
aoa_048  integer,
aoa_049  integer,
aoa_050  integer,
aoa_051  integer,
aoa_052  integer,
aoa_053  integer,
aoa_054  integer,
aoa_055  integer,
aoa_056  integer,
aoa_057  integer,
aoa_058  integer,
aoa_059  integer,
aoa_060  integer,
aoa_061  integer,
aoa_062  integer,
aoa_063  integer,
aoa_064  integer,
aoa_065  integer,
aoa_066  integer,
aoa_067  integer,
aoa_068  integer,
aoa_069  integer,
aoa_070  integer,
aoa_071  integer,
aoa_072  integer,
aoa_073  integer,
aoa_074  integer,
aoa_075  integer,
aoa_076  integer,
aoa_077  integer,
aoa_078  integer,
aoa_079  integer,
aoa_080  integer,
aoa_081  integer,
aoa_082  integer,
aoa_083  integer,
aoa_084  integer,
aoa_085  integer,
aoa_086  integer,
aoa_087  integer,
aoa_088  integer,
aoa_089  integer,
aoa_090  integer,
aoa_091  integer,
aoa_092  integer,
aoa_093  integer,
aoa_094  integer,
aoa_095  integer,
aoa_096  integer,
aoa_097  integer,
aoa_098  integer,
aoa_099  integer,
aoa_100  integer,
aoa_101  integer,
aoa_102  integer,
aoa_103  integer,
aoa_104  integer,
aoa_105  integer,
aoa_106  integer,
aoa_107  integer,
aoa_108  integer,
aoa_109  integer,
aoa_110  integer,
aoa_111  integer,
aoa_112  integer,
aoa_113  integer,
aoa_114  integer,
aoa_115  integer,
aoa_116  integer,
aoa_117  integer,
aoa_118  integer,
aoa_119  integer,
aoa_120  integer,
aoa_121  integer,
aoa_122  integer,
aoa_123  integer,
aoa_124  integer,
aoa_125  integer,
aoa_126  integer,
aoa_127  integer,
aoa_128  integer,
aoa_129  integer,
aoa_130  integer,
aoa_131  integer,
aoa_132  integer,
aoa_133  integer,
aoa_134  integer,
aoa_135  integer,
aoa_136  integer,
aoa_137  integer,
aoa_138  integer,
aoa_139  integer,
aoa_140  integer,
aoa_141  integer,
aoa_142  integer,
aoa_143  integer,
aoa_144  integer,
aoa_145  integer,
aoa_146  integer,
aoa_147  integer,
aoa_148  integer,
aoa_149  integer,
aoa_150  integer,
aoa_151  integer,
aoa_152  integer,
aoa_153  integer,
aoa_154  integer,
aoa_155  integer,
aoa_156  integer,
aoa_157  integer,
aoa_158  integer,
aoa_159  integer,
aoa_160  integer,
aoa_161  integer,
aoa_162  integer,
aoa_163  integer,
aoa_164  integer,
aoa_165  integer,
aoa_166  integer,
aoa_167  integer,
aoa_168  integer,
aoa_169  integer,
aoa_170  integer,
aoa_171  integer,
aoa_172  integer,
aoa_173  integer,
aoa_174  integer,
aoa_175  integer,
aoa_176  integer,
aoa_177  integer,
aoa_178  integer,
aoa_179  integer,
aoa_180  integer,
aoa_181  integer,
aoa_182  integer,
aoa_183  integer,
aoa_184  integer,
aoa_185  integer,
aoa_186  integer,
aoa_187  integer,
aoa_188  integer,
aoa_189  integer,
aoa_190  integer,
aoa_191  integer,
aoa_192  integer,
aoa_193  integer,
aoa_194  integer,
aoa_195  integer,
aoa_196  integer,
aoa_197  integer,
aoa_198  integer,
aoa_199  integer,
aoa_200  integer,
aoa_201  integer,
aoa_202  integer,
aoa_203  integer,
aoa_204  integer,
aoa_205  integer,
aoa_206  integer,
aoa_207  integer,
aoa_208  integer,
aoa_209  integer,
aoa_210  integer,
aoa_211  integer,
aoa_212  integer,
aoa_213  integer,
aoa_214  integer,
aoa_215  integer,
aoa_216  integer,
aoa_217  integer,
aoa_218  integer,
aoa_219  integer,
aoa_220  integer,
aoa_221  integer,
aoa_222  integer,
aoa_223  integer,
aoa_224  integer,
aoa_225  integer,
aoa_226  integer,
aoa_227  integer,
aoa_228  integer,
aoa_229  integer,
aoa_230  integer,
aoa_231  integer,
aoa_232  integer,
aoa_233  integer,
aoa_234  integer,
aoa_235  integer,
aoa_236  integer,
aoa_237  integer,
aoa_238  integer,
aoa_239  integer,
aoa_240  integer,
aoa_241  integer,
aoa_242  integer,
aoa_243  integer,
aoa_244  integer,
aoa_245  integer,
aoa_246  integer,
aoa_247  integer,
aoa_248  integer,
aoa_249  integer,
aoa_250  integer,
aoa_251  integer,
aoa_252  integer,
aoa_253  integer,
aoa_254  integer,
aoa_255  integer,
aoa_256  integer,
aoa_257  integer,
aoa_258  integer,
aoa_259  integer,
aoa_260  integer,
aoa_261  integer,
aoa_262  integer,
aoa_263  integer,
aoa_264  integer,
aoa_265  integer,
aoa_266  integer,
aoa_267  integer,
aoa_268  integer,
aoa_269  integer,
aoa_270  integer,
aoa_271  integer,
aoa_272  integer,
aoa_273  integer,
aoa_274  integer,
aoa_275  integer,
aoa_276  integer,
aoa_277  integer,
aoa_278  integer,
aoa_279  integer,
aoa_280  integer,
aoa_281  integer,
aoa_282  integer,
aoa_283  integer,
aoa_284  integer,
aoa_285  integer,
aoa_286  integer,
aoa_287  integer,
aoa_288  integer,
aoa_289  integer,
aoa_290  integer,
aoa_291  integer,
aoa_292  integer,
aoa_293  integer,
aoa_294  integer,
aoa_295  integer,
aoa_296  integer,
aoa_297  integer,
aoa_298  integer,
aoa_299  integer,
aoa_300  integer,
aoa_301  integer,
aoa_302  integer,
aoa_303  integer,
aoa_304  integer,
aoa_305  integer,
aoa_306  integer,
aoa_307  integer,
aoa_308  integer,
aoa_309  integer,
aoa_310  integer,
aoa_311  integer,
aoa_312  integer,
aoa_313  integer,
aoa_314  integer,
aoa_315  integer,
aoa_316  integer,
aoa_317  integer,
aoa_318  integer,
aoa_319  integer,
aoa_320  integer,
aoa_321  integer,
aoa_322  integer,
aoa_323  integer,
aoa_324  integer,
aoa_325  integer,
aoa_326  integer,
aoa_327  integer,
aoa_328  integer,
aoa_329  integer,
aoa_330  integer,
aoa_331  integer,
aoa_332  integer,
aoa_333  integer,
aoa_334  integer,
aoa_335  integer,
aoa_336  integer,
aoa_337  integer,
aoa_338  integer,
aoa_339  integer,
aoa_340  integer,
aoa_341  integer,
aoa_342  integer,
aoa_343  integer,
aoa_344  integer,
aoa_345  integer,
aoa_346  integer,
aoa_347  integer,
aoa_348  integer,
aoa_349  integer,
aoa_350  integer,
aoa_351  integer,
aoa_352  integer,
aoa_353  integer,
aoa_354  integer,
aoa_355  integer,
aoa_356  integer,
aoa_357  integer,
aoa_358  integer,
aoa_359  integer,
aoa_360  integer,
aoa_361  integer,
aoa_362  integer,
aoa_363  integer,
aoa_364  integer,
aoa_365  integer,
aoa_366  integer,
aoa_367  integer,
aoa_368  integer,
aoa_369  integer,
aoa_370  integer,
aoa_371  integer,
aoa_372  integer,
aoa_373  integer,
aoa_374  integer,
aoa_375  integer,
aoa_376  integer,
aoa_377  integer,
aoa_378  integer,
aoa_379  integer,
aoa_380  integer,
aoa_381  integer,
aoa_382  integer,
aoa_383  integer,
aoa_384  integer,
aoa_385  integer,
aoa_386  integer,
aoa_387  integer,
aoa_388  integer,
aoa_389  integer,
aoa_390  integer,
aoa_391  integer,
aoa_392  integer,
aoa_393  integer,
aoa_394  integer,
aoa_395  integer,
aoa_396  integer,
aoa_397  integer,
aoa_398  integer,
aoa_399  integer,
aoa_400  integer,
aoa_401  integer,
aoa_402  integer,
aoa_403  integer,
aoa_404  integer,
aoa_405  integer,
aoa_406  integer,
aoa_407  integer,
aoa_408  integer,
aoa_409  integer,
aoa_410  integer,
aoa_411  integer,
aoa_412  integer,
aoa_413  integer,
aoa_414  integer,
aoa_415  integer,
aoa_416  integer,
aoa_417  integer,
aoa_418  integer,
aoa_419  integer,
aoa_420  integer,
aoa_421  integer,
aoa_422  integer,
aoa_423  integer,
aoa_424  integer,
aoa_425  integer,
aoa_426  integer,
aoa_427  integer,
aoa_428  integer,
aoa_429  integer,
aoa_430  integer,
aoa_431  integer,
aoa_432  integer,
aoa_433  integer,
aoa_434  integer,
aoa_435  integer,
aoa_436  integer,
aoa_437  integer,
aoa_438  integer,
aoa_439  integer,
aoa_440  integer,
aoa_441  integer,
aoa_442  integer,
aoa_443  integer,
aoa_444  integer,
aoa_445  integer,
aoa_446  integer,
aoa_447  integer,
aoa_448  integer,
aoa_449  integer,
aoa_450  integer,
aoa_451  integer,
aoa_452  integer,
aoa_453  integer,
aoa_454  integer,
aoa_455  integer,
aoa_456  integer,
aoa_457  integer,
aoa_458  integer,
aoa_459  integer,
aoa_460  integer,
aoa_461  integer,
aoa_462  integer,
aoa_463  integer,
aoa_464  integer,
aoa_465  integer,
aoa_466  integer,
aoa_467  integer,
aoa_468  integer,
aoa_469  integer,
aoa_470  integer,
aoa_471  integer,
aoa_472  integer,
aoa_473  integer,
aoa_474  integer,
aoa_475  integer,
aoa_476  integer,
aoa_477  integer,
aoa_478  integer,
aoa_479  integer,
aoa_480  integer,
aoa_481  integer,
aoa_482  integer,
aoa_483  integer,
aoa_484  integer,
aoa_485  integer,
aoa_486  integer,
aoa_487  integer,
aoa_488  integer,
aoa_489  integer,
aoa_490  integer,
aoa_491  integer,
aoa_492  integer,
aoa_493  integer,
aoa_494  integer,
aoa_495  integer,
aoa_496  integer,
aoa_497  integer,
aoa_498  integer,
aoa_499  integer,
aoa_500  integer,
aoa_501  integer,
aoa_502  integer,
aoa_503  integer,
aoa_504  integer,
aoa_505  integer,
aoa_506  integer,
aoa_507  integer,
aoa_508  integer,
aoa_509  integer,
aoa_510  integer,
aoa_511  integer,
aoa_512  integer,
aoa_513  integer,
aoa_514  integer,
aoa_515  integer,
aoa_516  integer,
aoa_517  integer,
aoa_518  integer,
aoa_519  integer,
aoa_520  integer,
aoa_521  integer,
aoa_522  integer,
aoa_523  integer,
aoa_524  integer,
aoa_525  integer,
aoa_526  integer,
aoa_527  integer,
aoa_528  integer,
aoa_529  integer,
aoa_530  integer,
aoa_531  integer,
aoa_532  integer,
aoa_533  integer,
aoa_534  integer,
aoa_535  integer,
aoa_536  integer,
aoa_537  integer,
aoa_538  integer,
aoa_539  integer,
aoa_540  integer,
aoa_541  integer,
aoa_542  integer,
aoa_543  integer,
aoa_544  integer,
aoa_545  integer,
aoa_546  integer,
aoa_547  integer,
aoa_548  integer,
aoa_549  integer,
aoa_550  integer,
aoa_551  integer,
aoa_552  integer,
aoa_553  integer,
aoa_554  integer,
aoa_555  integer,
aoa_556  integer,
aoa_557  integer,
aoa_558  integer,
aoa_559  integer,
aoa_560  integer,
aoa_561  integer,
aoa_562  integer,
aoa_563  integer,
aoa_564  integer,
aoa_565  integer,
aoa_566  integer,
aoa_567  integer,
aoa_568  integer,
aoa_569  integer,
aoa_570  integer,
aoa_571  integer,
aoa_572  integer,
aoa_573  integer,
aoa_574  integer,
aoa_575  integer,
aoa_576  integer,
aoa_577  integer,
aoa_578  integer,
aoa_579  integer,
aoa_580  integer,
aoa_581  integer,
aoa_582  integer,
aoa_583  integer,
aoa_584  integer,
aoa_585  integer,
aoa_586  integer,
aoa_587  integer,
aoa_588  integer,
aoa_589  integer,
aoa_590  integer,
aoa_591  integer,
aoa_592  integer,
aoa_593  integer,
aoa_594  integer,
aoa_595  integer,
aoa_596  integer,
aoa_597  integer,
aoa_598  integer,
aoa_599  integer,
aoa_600  integer,
aoa_601  integer,
aoa_602  integer,
aoa_603  integer,
aoa_604  integer,
aoa_605  integer,
aoa_606  integer,
aoa_607  integer,
aoa_608  integer,
aoa_609  integer,
aoa_610  integer,
aoa_611  integer,
aoa_612  integer,
aoa_613  integer,
aoa_614  integer,
aoa_615  integer,
aoa_616  integer,
aoa_617  integer,
aoa_618  integer,
aoa_619  integer,
aoa_620  integer,
aoa_621  integer,
aoa_622  integer,
aoa_623  integer,
aoa_624  integer,
aoa_625  integer,
aoa_626  integer,
aoa_627  integer,
aoa_628  integer,
aoa_629  integer,
aoa_630  integer,
aoa_631  integer,
aoa_632  integer,
aoa_633  integer,
aoa_634  integer,
aoa_635  integer,
aoa_636  integer,
aoa_637  integer,
aoa_638  integer,
aoa_639  integer,
aoa_640  integer,
aoa_641  integer,
aoa_642  integer,
aoa_643  integer,
aoa_644  integer,
aoa_645  integer,
aoa_646  integer,
aoa_647  integer,
aoa_648  integer,
aoa_649  integer,
aoa_650  integer,
aoa_651  integer,
aoa_652  integer,
aoa_653  integer,
aoa_654  integer,
aoa_655  integer,
aoa_656  integer,
aoa_657  integer,
aoa_658  integer,
aoa_659  integer,
aoa_660  integer,
aoa_661  integer,
aoa_662  integer,
aoa_663  integer,
aoa_664  integer,
aoa_665  integer,
aoa_666  integer,
aoa_667  integer,
aoa_668  integer,
aoa_669  integer,
aoa_670  integer,
aoa_671  integer,
aoa_672  integer,
aoa_673  integer,
aoa_674  integer,
aoa_675  integer,
aoa_676  integer,
aoa_677  integer,
aoa_678  integer,
aoa_679  integer,
aoa_680  integer,
aoa_681  integer,
aoa_682  integer,
aoa_683  integer,
aoa_684  integer,
aoa_685  integer,
aoa_686  integer,
aoa_687  integer,
aoa_688  integer,
aoa_689  integer,
aoa_690  integer,
aoa_691  integer,
aoa_692  integer,
aoa_693  integer,
aoa_694  integer,
aoa_695  integer,
aoa_696  integer,
aoa_697  integer,
aoa_698  integer,
aoa_699  integer,
aoa_700  integer,
aoa_701  integer,
aoa_702  integer,
aoa_703  integer,
aoa_704  integer,
aoa_705  integer,
aoa_706  integer,
aoa_707  integer,
aoa_708  integer,
aoa_709  integer,
aoa_710  integer,
aoa_711  integer,
aoa_712  integer,
aoa_713  integer,
aoa_714  integer,
aoa_715  integer,
aoa_716  integer,
aoa_717  integer,
aoa_718  integer,
aoa_719  integer,
aoa_sum  number(38,8),
aoa_count  integer
);


